export const transactionsMock = [
  {
    numberOfInstallments: 10,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 8,
    description: 'Unidas Locadora Sa     Belo Horizont Bra',
    date: '2024-07-15',
    type: 'DEBIT',
    amount: 155.92,
  },
  {
    numberOfInstallments: 10,
    categoryIcon: 'OUTROS',
    currentInstallment: 3,
    description: 'Ser*de*verdade         Curitiba      Bra',
    date: '2024-07-15',
    type: 'DEBIT',
    amount: 218.15,
  },
  {
    numberOfInstallments: 5,
    categoryIcon: 'VESTUARIO',
    currentInstallment: 2,
    description: 'Amazon Marketplace     Sao Paulo     Bra',
    date: '2024-07-15',
    type: 'DEBIT',
    amount: 50.07,
  },
  {
    numberOfInstallments: 5,
    categoryIcon: 'OUTROS',
    currentInstallment: 2,
    description: 'Bstories2              Sao Paulo     Bra',
    date: '2024-07-15',
    type: 'DEBIT',
    amount: 34.71,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Condor Champagnat Lj',
    date: '2024-06-27',
    type: 'DEBIT',
    amount: 98.43,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-27',
    type: 'DEBIT',
    amount: 24.48,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-27',
    type: 'DEBIT',
    amount: 20.73,
  },
  {
    numberOfInstallments: 3,
    categoryIcon: 'COMPRAS',
    currentInstallment: 1,
    description: 'Casa China          ',
    date: '2024-06-26',
    type: 'DEBIT',
    amount: 23.3,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-25',
    type: 'DEBIT',
    amount: 20.64,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-25',
    type: 'DEBIT',
    amount: 22.25,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-24',
    type: 'DEBIT',
    amount: 34.64,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-24',
    type: 'DEBIT',
    amount: 32.71,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'PAGAMENTOS',
    currentInstallment: 0,
    description: 'Netflix.com         ',
    date: '2024-06-24',
    type: 'DEBIT',
    amount: 55.9,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Condor Champagnat Lj',
    date: '2024-06-23',
    type: 'DEBIT',
    amount: 148.56,
  },
  {
    numberOfInstallments: 2,
    categoryIcon: 'VESTUARIO',
    currentInstallment: 1,
    description: 'Amazon Br           ',
    date: '2024-06-23',
    type: 'DEBIT',
    amount: 74.82,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'RESTAURANTES',
    currentInstallment: 0,
    description: 'Costelaria Panza    ',
    date: '2024-06-22',
    type: 'DEBIT',
    amount: 163.8,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-22',
    type: 'DEBIT',
    amount: 23.34,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'CONSTRUCAO',
    currentInstallment: 0,
    description: 'Estok Distribuidora ',
    date: '2024-06-22',
    type: 'DEBIT',
    amount: 65.9,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-22',
    type: 'DEBIT',
    amount: 20.73,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-22',
    type: 'DEBIT',
    amount: 16.79,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'HOSPEDAGEM',
    currentInstallment: 0,
    description: 'Qoya Cwb            ',
    date: '2024-06-22',
    type: 'DEBIT',
    amount: 540.1,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'OUTROS',
    currentInstallment: 0,
    description: 'Daiso Brasil        ',
    date: '2024-06-21',
    type: 'DEBIT',
    amount: 23.97,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'OUTROS',
    currentInstallment: 0,
    description: 'Leo Cosmeticos      ',
    date: '2024-06-21',
    type: 'DEBIT',
    amount: 24.0,
  },
  {
    numberOfInstallments: 4,
    categoryIcon: 'OUTROS',
    currentInstallment: 1,
    description: 'Hna*oboticario      ',
    date: '2024-06-21',
    type: 'DEBIT',
    amount: 19.6,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'COMPRAS',
    currentInstallment: 0,
    description: 'Openai *chatgpt Subs',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 113.67,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'OUTROS',
    currentInstallment: 0,
    description: 'Iof Internacional',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 4.98,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'RESTAURANTES',
    currentInstallment: 0,
    description: 'Santo Grao          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 16.5,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'OUTROS',
    currentInstallment: 0,
    description: 'Vivo Easy           ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 1.3,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Restaurante Carmo Lt',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 49.86,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 12.73,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 17.67,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 40.29,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 17.57,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 20.71,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 28.32,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Super Beal          ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 10.25,
  },
  {
    numberOfInstallments: 3,
    categoryIcon: 'HOSPEDAGEM',
    currentInstallment: 1,
    description: 'Qoya Cwb            ',
    date: '2024-06-20',
    type: 'DEBIT',
    amount: 709.67,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Condor Champagnat Lj',
    date: '2024-06-19',
    type: 'DEBIT',
    amount: 146.6,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'RESTAURANTES',
    currentInstallment: 0,
    description: 'Doppo Cucina Restaur',
    date: '2024-06-19',
    type: 'DEBIT',
    amount: 540.1,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-19',
    type: 'DEBIT',
    amount: 19.42,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-19',
    type: 'DEBIT',
    amount: 18.96,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Ifd*otacilio Falkemb',
    date: '2024-06-17',
    type: 'DEBIT',
    amount: 140.99,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'PAGAMENTO_RECEBIDO',
    currentInstallment: 0,
    description: 'Pagamento Online De Fatura',
    date: '2024-06-16',
    type: 'CREDIT',
    amount: 6212.66,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'OUTROS',
    currentInstallment: 0,
    description: 'Assoc Torre De Vigia',
    date: '2024-06-16',
    type: 'DEBIT',
    amount: 1800.0,
  },
  {
    numberOfInstallments: 4,
    categoryIcon: 'DROGARIA',
    currentInstallment: 1,
    description: 'Farmacia Drog Nissei',
    date: '2024-06-16',
    type: 'DEBIT',
    amount: 36.92,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-15',
    type: 'DEBIT',
    amount: 24.18,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'SUPERMERCADO',
    currentInstallment: 0,
    description: 'Condor Champagnat Lj',
    date: '2024-06-15',
    type: 'DEBIT',
    amount: 82.99,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 0,
    description: 'Uber* Trip          ',
    date: '2024-06-15',
    type: 'DEBIT',
    amount: 21.55,
  },
  {
    numberOfInstallments: 0,
    categoryIcon: 'RESTAURANTES',
    currentInstallment: 0,
    description: 'Ifd*sakai Burger Alt',
    date: '2024-06-14',
    type: 'DEBIT',
    amount: 153.69,
  },
  {
    numberOfInstallments: 6,
    categoryIcon: 'DROGARIA',
    currentInstallment: 3,
    description: 'Farmacia Drog Nissei',
    date: '2024-04-16',
    type: 'DEBIT',
    amount: 33.12,
  },
  {
    numberOfInstallments: 9,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 4,
    description: 'Movida Rac          ',
    date: '2024-03-21',
    type: 'DEBIT',
    amount: 51.99,
  },
  {
    numberOfInstallments: 10,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 5,
    description: 'Movida Rac          ',
    date: '2024-02-26',
    type: 'DEBIT',
    amount: 57.79,
  },
  {
    numberOfInstallments: 10,
    categoryIcon: 'COMPRAS',
    currentInstallment: 5,
    description: 'Vivara Ctb          ',
    date: '2024-02-22',
    type: 'DEBIT',
    amount: 224.0,
  },
  {
    numberOfInstallments: 7,
    categoryIcon: 'TRANSPORTE',
    currentInstallment: 5,
    description: 'Movida Rac          ',
    date: '2024-02-19',
    type: 'DEBIT',
    amount: 56.8,
  },
  {
    numberOfInstallments: 10,
    categoryIcon: 'OUTROS',
    currentInstallment: 6,
    description: 'Maquineta Virtual   ',
    date: '2024-01-20',
    type: 'DEBIT',
    amount: 218.15,
  },
];
